// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import NotificacionesController from "./notificaciones_controller"
application.register("notificaciones", NotificacionesController)

import RolesController from "./roles_controller"
application.register("roles", RolesController)
