require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'bin/*'

Bundler/OrderedGems:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 20
  Exclude:
  - 'db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'config/routes.rb'
    - 'config/environments/*'

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/migrate/*'

Rails/ContentTag:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Rails/Present:
  Exclude:
    - 'bin/*'

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'test/**/*'
    - 'db/migrate/*'

Style/EmptyMethod:
  EnforcedStyle: expanded

# En vez de requerir un magic comment en cada archivo, configuramos nuestro
# entorno para que por default todas las string sean frozen:
#
#   export RUBYOPT=--enable-frozen-string-literal
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StderrPuts:
  Exclude:
    - 'bin/*'

Style/SymbolArray:
  EnforcedStyle: brackets
